// Fake data for pet sitters (50 records)
const sittersData = [
  {
    id: 1,
    name: "Đỗ Tùng",
    type: "Căn hộ",
    price: 150000,
    rating: 4.5,
    reviewCount: 312,
    location: "Hải Châu, Đà Nẵng",
    status: "Hiện đang giữ 1 mèo",
    amenities: ["Điều Hòa", "Đồ ăn thưởng miễn phí"],
    petType: ["cat"],
    personality: ["friendly"],
    specialNeeds: ["none"],
    experienceLevel: "professional",
    diet: ["normal"],
    environment: "indoor-only",
    availability: ["morning", "afternoon"],
    image: "images/pet_sitter_poodle.png"
  },
  {
    id: 2,
    name: "Minh Nhật",
    type: "Nhà riêng",
    price: 200000,
    rating: 5.0,
    reviewCount: 1310,
    location: "Thanh Khê, Đà Nẵng",
    status: "Hiện đang giữ 3 mèo",
    amenities: ["Điều Hòa", "Máy lọc không khí", "Đồ chơi miễn phí"],
    petType: ["cat", "dog"],
    personality: ["friendly", "active"],
    specialNeeds: ["none"],
    experienceLevel: "professional",
    diet: ["normal", "strict-diet"],
    environment: "can-go-outside",
    availability: ["all-day"],
    image: "images/home_with_cats.png"
  },
  {
    id: 3,
    name: "Cat Moon Hotel",
    type: "Khách sạn thú cưng",
    price: 175000,
    rating: 5.0,
    reviewCount: 301,
    location: "Sơn Trà, Đà Nẵng",
    status: "Hiện đang giữ 5 mèo",
    amenities: ["Vệ sinh miễn phí", "Tư vấn chế độ ăn"],
    petType: ["cat"],
    personality: ["friendly", "shy"],
    specialNeeds: ["medical-care"],
    experienceLevel: "medical-experience",
    diet: ["normal", "strict-diet"],
    environment: "indoor-only",
    availability: ["all-day"],
    image: "images/pet_hotel_building.png"
  },
  {
    id: 4,
    name: "Phương Anh",
    type: "Căn hộ",
    price: 120000,
    rating: 4.8,
    reviewCount: 89,
    location: "Hải Châu, Đà Nẵng",
    status: "Sẵn sàng nhận thêm",
    amenities: ["Camera giám sát", "Sân vườn nhỏ"],
    petType: ["dog"],
    personality: ["active", "aggressive"],
    specialNeeds: ["none"],
    experienceLevel: "basic",
    diet: ["normal"],
    environment: "can-go-outside",
    availability: ["afternoon"],
    image: "images/pet_sitter_poodle.png"
  },
  {
    id: 5,
    name: "Tuấn Kiệt",
    type: "Nhà riêng",
    price: 180000,
    rating: 4.9,
    reviewCount: 456,
    location: "Cẩm Lệ, Đà Nẵng",
    status: "Hiện đang giữ 2 chó",
    amenities: ["Sân vườn rộng", "Dắt đi dạo miễn phí"],
    petType: ["dog"],
    personality: ["friendly", "active"],
    specialNeeds: ["none"],
    experienceLevel: "professional",
    diet: ["normal"],
    environment: "can-go-outside",
    availability: ["morning", "afternoon"],
    image: "images/home_with_cats.png"
  },
  {
    id: 6,
    name: "Thanh Hà",
    type: "Căn hộ",
    price: 160000,
    rating: 4.7,
    reviewCount: 234,
    location: "Thanh Khê, Đà Nẵng",
    status: "Sẵn sàng nhận thêm",
    amenities: ["Điều Hòa", "Đồ chơi"],
    petType: ["cat"],
    personality: ["shy"],
    specialNeeds: ["medication"],
    experienceLevel: "experienced-with-shy",
    diet: ["restricted-food"],
    environment: "indoor-only",
    availability: ["morning"],
    image: "images/pet_hotel_building.png"
  },
  {
    id: 7,
    name: "Hồng Quân",
    type: "Nhà riêng",
    price: 220000,
    rating: 5.0,
    reviewCount: 567,
    location: "Ngũ Hành Sơn, Đà Nẵng",
    status: "Hiện đang giữ 1 chó",
    amenities: ["Bể bơi mini", "Spa thú cưng"],
    petType: ["dog"],
    personality: ["friendly"],
    specialNeeds: ["senior-pet"],
    experienceLevel: "medical-experience",
    diet: ["strict-diet"],
    environment: "can-go-outside",
    availability: ["all-day"],
    image: "images/pet_sitter_poodle.png"
  },
  {
    id: 8,
    name: "Như Ý",
    type: "Căn hộ",
    price: 135000,
    rating: 4.6,
    reviewCount: 178,
    location: "Hải Châu, Đà Nẵng",
    status: "Sẵn sàng nhận thêm",
    amenities: ["Camera 24/7", "Báo cáo hàng ngày"],
    petType: ["cat"],
    personality: ["friendly", "shy"],
    specialNeeds: ["none"],
    experienceLevel: "experienced-with-shy",
    diet: ["normal"],
    environment: "indoor-only",
    availability: ["afternoon"],
    image: "images/home_with_cats.png"
  },
  {
    id: 9,
    name: "Duy Khang",
    type: "Khách sạn thú cưng",
    price: 195000,
    rating: 4.9,
    reviewCount: 723,
    location: "Sơn Trà, Đà Nẵng",
    status: "Hiện đang giữ 8 mèo",
    amenities: ["Phòng riêng biệt", "Khám sức khỏe định kỳ"],
    petType: ["cat", "dog"],
    personality: ["friendly", "active"],
    specialNeeds: ["medical-care"],
    experienceLevel: "medical-experience",
    diet: ["normal", "strict-diet", "restricted-food"],
    environment: "indoor-only",
    availability: ["all-day"],
    image: "images/pet_hotel_building.png"
  },
  {
    id: 10,
    name: "Mai Phương",
    type: "Căn hộ",
    price: 145000,
    rating: 4.8,
    reviewCount: 201,
    location: "Thanh Khê, Đà Nẵng",
    status: "Sẵn sàng nhận thêm",
    amenities: ["Điều Hòa", "Đồ chơi thông minh"],
    petType: ["cat"],
    personality: ["friendly"],
    specialNeeds: ["none"],
    experienceLevel: "basic",
    diet: ["normal"],
    environment: "indoor-only",
    availability: ["morning", "afternoon"],
    image: "images/pet_sitter_poodle.png"
  },
  {
    id: 11,
    name: "Quốc Anh",
    type: "Nhà riêng",
    price: 210000,
    rating: 5.0,
    reviewCount: 445,
    location: "Cẩm Lệ, Đà Nẵng",
    status: "Hiện đang giữ 3 chó",
    amenities: ["Sân vườn lớn", "Huấn luyện cơ bản"],
    petType: ["dog"],
    personality: ["aggressive", "active"],
    specialNeeds: ["none"],
    experienceLevel: "professional",
    diet: ["normal"],
    environment: "can-go-outside",
    availability: ["all-day"],
    image: "images/home_with_cats.png"
  },
  {
    id: 12,
    name: "Bảo Trâm",
    type: "Căn hộ",
    price: 155000,
    rating: 4.7,
    reviewCount: 167,
    location: "Hải Châu, Đà Nẵng",
    status: "Sẵn sàng nhận thêm",
    amenities: ["Máy lọc không khí", "Tủ lạnh riêng"],
    petType: ["cat"],
    personality: ["shy"],
    specialNeeds: ["medication"],
    experienceLevel: "experienced-with-shy",
    diet: ["restricted-food"],
    environment: "indoor-only",
    availability: ["morning"],
    image: "images/pet_hotel_building.png"
  },
  {
    id: 13,
    name: "Thành Đạt",
    type: "Nhà riêng",
    price: 190000,
    rating: 4.9,
    reviewCount: 389,
    location: "Ngũ Hành Sơn, Đà Nẵng",
    status: "Hiện đang giữ 2 mèo",
    amenities: ["Cây cào móng", "Phòng chơi riêng"],
    petType: ["cat"],
    personality: ["friendly", "active"],
    specialNeeds: ["none"],
    experienceLevel: "professional",
    diet: ["normal"],
    environment: "indoor-only",
    availability: ["afternoon"],
    image: "images/pet_sitter_poodle.png"
  },
  {
    id: 14,
    name: "Ngọc Lan",
    type: "Căn hộ",
    price: 140000,
    rating: 4.6,
    reviewCount: 156,
    location: "Thanh Khê, Đà Nẵng",
    status: "Sẵn sàng nhận thêm",
    amenities: ["Camera giám sát", "Cửa sổ thoáng mát"],
    petType: ["cat"],
    personality: ["friendly"],
    specialNeeds: ["none"],
    experienceLevel: "basic",
    diet: ["normal"],
    environment: "indoor-only",
    availability: ["all-day"],
    image: "images/home_with_cats.png"
  },
  {
    id: 15,
    name: "Văn Hoàng",
    type: "Khách sạn thú cưng",
    price: 230000,
    rating: 5.0,
    reviewCount: 892,
    location: "Sơn Trà, Đà Nẵng",
    status: "Hiện đang giữ 12 thú cưng",
    amenities: ["Bác sĩ thú y 24/7", "Spa cao cấp"],
    petType: ["cat", "dog"],
    personality: ["friendly", "shy", "aggressive", "active"],
    specialNeeds: ["medical-care", "medication", "senior-pet"],
    experienceLevel: "medical-experience",
    diet: ["normal", "strict-diet", "restricted-food"],
    environment: "indoor-only",
    availability: ["all-day"],
    image: "images/pet_hotel_building.png"
  },
  {
    id: 16,
    name: "Thu Hương",
    type: "Căn hộ",
    price: 165000,
    rating: 4.8,
    reviewCount: 278,
    location: "Hải Châu, Đà Nẵng",
    status: "Sẵn sàng nhận thêm",
    amenities: ["Điều Hòa", "Đồ ăn organic"],
    petType: ["cat"],
    personality: ["friendly"],
    specialNeeds: ["none"],
    experienceLevel: "professional",
    diet: ["strict-diet"],
    environment: "indoor-only",
    availability: ["morning", "afternoon"],
    image: "images/pet_sitter_poodle.png"
  },
  {
    id: 17,
    name: "Minh Tuấn",
    type: "Nhà riêng",
    price: 185000,
    rating: 4.9,
    reviewCount: 534,
    location: "Cẩm Lệ, Đà Nẵng",
    status: "Hiện đang giữ 1 chó",
    amenities: ["Sân tập luyện", "Đồ chơi đa dạng"],
    petType: ["dog"],
    personality: ["active"],
    specialNeeds: ["none"],
    experienceLevel: "professional",
    diet: ["normal"],
    environment: "can-go-outside",
    availability: ["morning", "afternoon"],
    image: "images/home_with_cats.png"
  },
  {
    id: 18,
    name: "Hải Yến",
    type: "Căn hộ",
    price: 130000,
    rating: 4.5,
    reviewCount: 123,
    location: "Thanh Khê, Đà Nẵng",
    status: "Sẵn sàng nhận thêm",
    amenities: ["Camera", "Điều Hòa"],
    petType: ["cat"],
    personality: ["shy"],
    specialNeeds: ["none"],
    experienceLevel: "experienced-with-shy",
    diet: ["normal"],
    environment: "indoor-only",
    availability: ["afternoon"],
    image: "images/pet_hotel_building.png"
  },
  {
    id: 19,
    name: "Đức Mạnh",
    type: "Nhà riêng",
    price: 205000,
    rating: 5.0,
    reviewCount: 678,
    location: "Ngũ Hành Sơn, Đà Nẵng",
    status: "Hiện đang giữ 4 chó",
    amenities: ["Sân vườn rộng", "Bể tắm riêng"],
    petType: ["dog"],
    personality: ["friendly", "active"],
    specialNeeds: ["none"],
    experienceLevel: "professional",
    diet: ["normal"],
    environment: "can-go-outside",
    availability: ["all-day"],
    image: "images/pet_sitter_poodle.png"
  },
  {
    id: 20,
    name: "Thùy Linh",
    type: "Căn hộ",
    price: 125000,
    rating: 4.6,
    reviewCount: 145,
    location: "Hải Châu, Đà Nẵng",
    status: "Sẵn sàng nhận thêm",
    amenities: ["Máy lọc không khí", "Đồ chơi"],
    petType: ["cat"],
    personality: ["friendly"],
    specialNeeds: ["none"],
    experienceLevel: "basic",
    diet: ["normal"],
    environment: "indoor-only",
    availability: ["morning"],
    image: "images/home_with_cats.png"
  },
  {
    id: 21,
    name: "Anh Tuấn",
    type: "Khách sạn thú cưng",
    price: 240000,
    rating: 5.0,
    reviewCount: 1045,
    location: "Sơn Trà, Đà Nẵng",
    status: "Hiện đang giữ 15 thú cưng",
    amenities: ["Phòng VIP", "Bác sĩ thú y", "Spa"],
    petType: ["cat", "dog"],
    personality: ["friendly", "shy", "active"],
    specialNeeds: ["medical-care", "senior-pet"],
    experienceLevel: "medical-experience",
    diet: ["normal", "strict-diet"],
    environment: "indoor-only",
    availability: ["all-day"],
    image: "images/pet_hotel_building.png"
  },
  {
    id: 22,
    name: "Phương Thảo",
    type: "Căn hộ",
    price: 148000,
    rating: 4.7,
    reviewCount: 189,
    location: "Thanh Khê, Đà Nẵng",
    status: "Sẵn sàng nhận thêm",
    amenities: ["Điều Hòa", "Camera"],
    petType: ["cat"],
    personality: ["friendly", "shy"],
    specialNeeds: ["medication"],
    experienceLevel: "experienced-with-shy",
    diet: ["restricted-food"],
    environment: "indoor-only",
    availability: ["afternoon"],
    image: "images/pet_sitter_poodle.png"
  },
  {
    id: 23,
    name: "Tuấn Anh",
    type: "Nhà riêng",
    price: 195000,
    rating: 4.9,
    reviewCount: 423,
    location: "Cẩm Lệ, Đà Nẵng",
    status: "Hiện đang giữ 2 chó",
    amenities: ["Sân chơi", "Huấn luyện"],
    petType: ["dog"],
    personality: ["active", "aggressive"],
    specialNeeds: ["none"],
    experienceLevel: "professional",
    diet: ["normal"],
    environment: "can-go-outside",
    availability: ["morning", "afternoon"],
    image: "images/home_with_cats.png"
  },
  {
    id: 24,
    name: "Khánh Ly",
    type: "Căn hộ",
    price: 158000,
    rating: 4.8,
    reviewCount: 267,
    location: "Hải Châu, Đà Nẵng",
    status: "Sẵn sàng nhận thêm",
    amenities: ["Cửa sổ lớn", "Cây cào móng"],
    petType: ["cat"],
    personality: ["friendly"],
    specialNeeds: ["none"],
    experienceLevel: "professional",
    diet: ["normal"],
    environment: "indoor-only",
    availability: ["all-day"],
    image: "images/pet_hotel_building.png"
  },
  {
    id: 25,
    name: "Hoàng Long",
    type: "Nhà riêng",
    price: 215000,
    rating: 5.0,
    reviewCount: 756,
    location: "Ngũ Hành Sơn, Đà Nẵng",
    status: "Hiện đang giữ 3 thú cưng",
    amenities: ["Sân vườn", "Bể bơi", "Spa"],
    petType: ["dog"],
    personality: ["friendly", "active"],
    specialNeeds: ["senior-pet"],
    experienceLevel: "medical-experience",
    diet: ["strict-diet"],
    environment: "can-go-outside",
    availability: ["all-day"],
    image: "images/pet_sitter_poodle.png"
  },
  {
    id: 26,
    name: "Ngọc Anh",
    type: "Căn hộ",
    price: 142000,
    rating: 4.6,
    reviewCount: 198,
    location: "Thanh Khê, Đà Nẵng",
    status: "Sẵn sàng nhận thêm",
    amenities: ["Điều Hòa", "Đồ chơi"],
    petType: ["cat"],
    personality: ["shy"],
    specialNeeds: ["none"],
    experienceLevel: "experienced-with-shy",
    diet: ["normal"],
    environment: "indoor-only",
    availability: ["morning"],
    image: "images/home_with_cats.png"
  },
  {
    id: 27,
    name: "Quang Minh",
    type: "Khách sạn thú cưng",
    price: 188000,
    rating: 4.9,
    reviewCount: 534,
    location: "Sơn Trà, Đà Nẵng",
    status: "Hiện đang giữ 9 mèo",
    amenities: ["Phòng riêng", "Camera 24/7"],
    petType: ["cat"],
    personality: ["friendly", "shy"],
    specialNeeds: ["medical-care"],
    experienceLevel: "medical-experience",
    diet: ["normal", "strict-diet"],
    environment: "indoor-only",
    availability: ["all-day"],
    image: "images/pet_hotel_building.png"
  },
  {
    id: 28,
    name: "Hồng Ngọc",
    type: "Căn hộ",
    price: 137000,
    rating: 4.7,
    reviewCount: 176,
    location: "Hải Châu, Đà Nẵng",
    status: "Sẵn sàng nhận thêm",
    amenities: ["Máy lọc không khí", "Camera"],
    petType: ["cat"],
    personality: ["friendly"],
    specialNeeds: ["none"],
    experienceLevel: "basic",
    diet: ["normal"],
    environment: "indoor-only",
    availability: ["afternoon"],
    image: "images/pet_sitter_poodle.png"
  },
  {
    id: 29,
    name: "Việt Anh",
    type: "Nhà riêng",
    price: 198000,
    rating: 4.9,
    reviewCount: 467,
    location: "Cẩm Lệ, Đà Nẵng",
    status: "Hiện đang giữ 2 chó",
    amenities: ["Sân vườn", "Dắt đi dạo"],
    petType: ["dog"],
    personality: ["friendly", "active"],
    specialNeeds: ["none"],
    experienceLevel: "professional",
    diet: ["normal"],
    environment: "can-go-outside",
    availability: ["morning", "afternoon"],
    image: "images/home_with_cats.png"
  },
  {
    id: 30,
    name: "Thanh Tâm",
    type: "Căn hộ",
    price: 153000,
    rating: 4.8,
    reviewCount: 223,
    location: "Thanh Khê, Đà Nẵng",
    status: "Sẵn sàng nhận thêm",
    amenities: ["Điều Hòa", "Cửa sổ view đẹp"],
    petType: ["cat"],
    personality: ["friendly"],
    specialNeeds: ["none"],
    experienceLevel: "professional",
    diet: ["normal"],
    environment: "indoor-only",
    availability: ["all-day"],
    image: "images/pet_hotel_building.png"
  },
  {
    id: 31,
    name: "Đức Thịnh",
    type: "Nhà riêng",
    price: 225000,
    rating: 5.0,
    reviewCount: 834,
    location: "Ngũ Hành Sơn, Đà Nẵng",
    status: "Hiện đang giữ 4 thú cưng",
    amenities: ["Sân vườn lớn", "Bác sĩ thú y"],
    petType: ["cat", "dog"],
    personality: ["friendly", "active"],
    specialNeeds: ["medical-care", "medication"],
    experienceLevel: "medical-experience",
    diet: ["normal", "strict-diet"],
    environment: "can-go-outside",
    availability: ["all-day"],
    image: "images/pet_sitter_poodle.png"
  },
  {
    id: 32,
    name: "Minh Châu",
    type: "Căn hộ",
    price: 143000,
    rating: 4.6,
    reviewCount: 187,
    location: "Hải Châu, Đà Nẵng",
    status: "Sẵn sàng nhận thêm",
    amenities: ["Camera", "Đồ chơi"],
    petType: ["cat"],
    personality: ["shy"],
    specialNeeds: ["medication"],
    experienceLevel: "experienced-with-shy",
    diet: ["restricted-food"],
    environment: "indoor-only",
    availability: ["morning"],
    image: "images/home_with_cats.png"
  },
  {
    id: 33,
    name: "Trung Kiên",
    type: "Khách sạn thú cưng",
    price: 208000,
    rating: 4.9,
    reviewCount: 645,
    location: "Sơn Trà, Đà Nẵng",
    status: "Hiện đang giữ 11 thú cưng",
    amenities: ["Phòng VIP", "Khám sức khỏe"],
    petType: ["cat", "dog"],
    personality: ["friendly", "shy", "active"],
    specialNeeds: ["medical-care"],
    experienceLevel: "medical-experience",
    diet: ["normal", "strict-diet"],
    environment: "indoor-only",
    availability: ["all-day"],
    image: "images/pet_hotel_building.png"
  },
  {
    id: 34,
    name: "Bích Ngọc",
    type: "Căn hộ",
    price: 168000,
    rating: 4.8,
    reviewCount: 289,
    location: "Thanh Khê, Đà Nẵng",
    status: "Sẵn sàng nhận thêm",
    amenities: ["Điều Hòa", "Máy lọc không khí"],
    petType: ["cat"],
    personality: ["friendly"],
    specialNeeds: ["none"],
    experienceLevel: "professional",
    diet: ["normal"],
    environment: "indoor-only",
    availability: ["morning", "afternoon"],
    image: "images/pet_sitter_poodle.png"
  },
  {
    id: 35,
    name: "Huy Hoàng",
    type: "Nhà riêng",
    price: 192000,
    rating: 4.9,
    reviewCount: 512,
    location: "Cẩm Lệ, Đà Nẵng",
    status: "Hiện đang giữ 3 chó",
    amenities: ["Sân chơi", "Bể tắm"],
    petType: ["dog"],
    personality: ["active", "aggressive"],
    specialNeeds: ["none"],
    experienceLevel: "professional",
    diet: ["normal"],
    environment: "can-go-outside",
    availability: ["afternoon"],
    image: "images/home_with_cats.png"
  },
  {
    id: 36,
    name: "Lan Anh",
    type: "Căn hộ",
    price: 134000,
    rating: 4.5,
    reviewCount: 154,
    location: "Hải Châu, Đà Nẵng",
    status: "Sẵn sàng nhận thêm",
    amenities: ["Camera", "Điều Hòa"],
    petType: ["cat"],
    personality: ["friendly", "shy"],
    specialNeeds: ["none"],
    experienceLevel: "basic",
    diet: ["normal"],
    environment: "indoor-only",
    availability: ["morning"],
    image: "images/pet_hotel_building.png"
  },
  {
    id: 37,
    name: "Công Phượng",
    type: "Nhà riêng",
    price: 235000,
    rating: 5.0,
    reviewCount: 923,
    location: "Ngũ Hành Sơn, Đà Nẵng",
    status: "Hiện đang giữ 5 thú cưng",
    amenities: ["Sân vườn", "Bể bơi", "Spa cao cấp"],
    petType: ["dog"],
    personality: ["friendly", "active"],
    specialNeeds: ["senior-pet"],
    experienceLevel: "medical-experience",
    diet: ["strict-diet"],
    environment: "can-go-outside",
    availability: ["all-day"],
    image: "images/pet_sitter_poodle.png"
  },
  {
    id: 38,
    name: "Thu Trang",
    type: "Căn hộ",
    price: 147000,
    rating: 4.7,
    reviewCount: 212,
    location: "Thanh Khê, Đà Nẵng",
    status: "Sẵn sàng nhận thêm",
    amenities: ["Máy lọc không khí", "Cây cào móng"],
    petType: ["cat"],
    personality: ["friendly"],
    specialNeeds: ["none"],
    experienceLevel: "professional",
    diet: ["normal"],
    environment: "indoor-only",
    availability: ["afternoon"],
    image: "images/home_with_cats.png"
  },
  {
    id: 39,
    name: "Minh Quân",
    type: "Khách sạn thú cưng",
    price: 218000,
    rating: 5.0,
    reviewCount: 778,
    location: "Sơn Trà, Đà Nẵng",
    status: "Hiện đang giữ 13 thú cưng",
    amenities: ["Bác sĩ thú y 24/7", "Phòng riêng cao cấp"],
    petType: ["cat", "dog"],
    personality: ["friendly", "shy", "aggressive", "active"],
    specialNeeds: ["medical-care", "medication", "senior-pet"],
    experienceLevel: "medical-experience",
    diet: ["normal", "strict-diet", "restricted-food"],
    environment: "indoor-only",
    availability: ["all-day"],
    image: "images/pet_hotel_building.png"
  },
  {
    id: 40,
    name: "Hải Yến",
    type: "Căn hộ",
    price: 159000,
    rating: 4.8,
    reviewCount: 245,
    location: "Hải Châu, Đà Nẵng",
    status: "Sẵn sàng nhận thêm",
    amenities: ["Điều Hòa", "Camera giám sát"],
    petType: ["cat"],
    personality: ["shy"],
    specialNeeds: ["medication"],
    experienceLevel: "experienced-with-shy",
    diet: ["restricted-food"],
    environment: "indoor-only",
    availability: ["morning"],
    image: "images/pet_sitter_poodle.png"
  },
  {
    id: 41,
    name: "Tuấn Đạt",
    type: "Nhà riêng",
    price: 202000,
    rating: 4.9,
    reviewCount: 589,
    location: "Cẩm Lệ, Đà Nẵng",
    status: "Hiện đang giữ 2 chó",
    amenities: ["Sân vườn", "Huấn luyện cơ bản"],
    petType: ["dog"],
    personality: ["friendly", "active"],
    specialNeeds: ["none"],
    experienceLevel: "professional",
    diet: ["normal"],
    environment: "can-go-outside",
    availability: ["morning", "afternoon"],
    image: "images/home_with_cats.png"
  },
  {
    id: 42,
    name: "Phương Linh",
    type: "Căn hộ",
    price: 138000,
    rating: 4.6,
    reviewCount: 167,
    location: "Thanh Khê, Đà Nẵng",
    status: "Sẵn sàng nhận thêm",
    amenities: ["Cửa sổ lớn", "Đồ chơi"],
    petType: ["cat"],
    personality: ["friendly"],
    specialNeeds: ["none"],
    experienceLevel: "basic",
    diet: ["normal"],
    environment: "indoor-only",
    availability: ["all-day"],
    image: "images/pet_hotel_building.png"
  },
  {
    id: 43,
    name: "Anh Khoa",
    type: "Nhà riêng",
    price: 213000,
    rating: 5.0,
    reviewCount: 712,
    location: "Ngũ Hành Sơn, Đà Nẵng",
    status: "Hiện đang giữ 4 chó",
    amenities: ["Sân vườn rộng", "Bể bơi"],
    petType: ["dog"],
    personality: ["friendly", "active"],
    specialNeeds: ["senior-pet"],
    experienceLevel: "medical-experience",
    diet: ["strict-diet"],
    environment: "can-go-outside",
    availability: ["all-day"],
    image: "images/pet_sitter_poodle.png"
  },
  {
    id: 44,
    name: "Ngọc Mai",
    type: "Căn hộ",
    price: 151000,
    rating: 4.7,
    reviewCount: 234,
    location: "Hải Châu, Đà Nẵng",
    status: "Sẵn sàng nhận thêm",
    amenities: ["Điều Hòa", "Máy lọc không khí"],
    petType: ["cat"],
    personality: ["friendly", "shy"],
    specialNeeds: ["none"],
    experienceLevel: "experienced-with-shy",
    diet: ["normal"],
    environment: "indoor-only",
    availability: ["afternoon"],
    image: "images/home_with_cats.png"
  },
  {
    id: 45,
    name: "Hoàng Nam",
    type: "Khách sạn thú cưng",
    price: 198000,
    rating: 4.9,
    reviewCount: 623,
    location: "Sơn Trà, Đà Nẵng",
    status: "Hiện đang giữ 10 thú cưng",
    amenities: ["Phòng riêng", "Khám sức khỏe định kỳ"],
    petType: ["cat", "dog"],
    personality: ["friendly", "active"],
    specialNeeds: ["medical-care"],
    experienceLevel: "medical-experience",
    diet: ["normal", "strict-diet"],
    environment: "indoor-only",
    availability: ["all-day"],
    image: "images/pet_hotel_building.png"
  },
  {
    id: 46,
    name: "Thanh Huyền",
    type: "Căn hộ",
    price: 144000,
    rating: 4.6,
    reviewCount: 198,
    location: "Thanh Khê, Đà Nẵng",
    status: "Sẵn sàng nhận thêm",
    amenities: ["Camera", "Đồ chơi thông minh"],
    petType: ["cat"],
    personality: ["friendly"],
    specialNeeds: ["none"],
    experienceLevel: "basic",
    diet: ["normal"],
    environment: "indoor-only",
    availability: ["morning"],
    image: "images/pet_sitter_poodle.png"
  },
  {
    id: 47,
    name: "Văn Thành",
    type: "Nhà riêng",
    price: 207000,
    rating: 4.9,
    reviewCount: 556,
    location: "Cẩm Lệ, Đà Nẵng",
    status: "Hiện đang giữ 3 chó",
    amenities: ["Sân chơi", "Dắt đi dạo hàng ngày"],
    petType: ["dog"],
    personality: ["active", "aggressive"],
    specialNeeds: ["none"],
    experienceLevel: "professional",
    diet: ["normal"],
    environment: "can-go-outside",
    availability: ["morning", "afternoon"],
    image: "images/home_with_cats.png"
  },
  {
    id: 48,
    name: "Kim Ngân",
    type: "Căn hộ",
    price: 162000,
    rating: 4.8,
    reviewCount: 276,
    location: "Hải Châu, Đà Nẵng",
    status: "Sẵn sàng nhận thêm",
    amenities: ["Điều Hòa", "Cây cào móng"],
    petType: ["cat"],
    personality: ["friendly"],
    specialNeeds: ["none"],
    experienceLevel: "professional",
    diet: ["normal"],
    environment: "indoor-only",
    availability: ["all-day"],
    image: "images/pet_hotel_building.png"
  },
  {
    id: 49,
    name: "Quốc Bảo",
    type: "Nhà riêng",
    price: 228000,
    rating: 5.0,
    reviewCount: 867,
    location: "Ngũ Hành Sơn, Đà Nẵng",
    status: "Hiện đang giữ 5 thú cưng",
    amenities: ["Sân vườn", "Bể bơi", "Bác sĩ thú y"],
    petType: ["cat", "dog"],
    personality: ["friendly", "active"],
    specialNeeds: ["medical-care", "senior-pet"],
    experienceLevel: "medical-experience",
    diet: ["normal", "strict-diet"],
    environment: "can-go-outside",
    availability: ["all-day"],
    image: "images/pet_sitter_poodle.png"
  },
  {
    id: 50,
    name: "Thúy Hằng",
    type: "Căn hộ",
    price: 156000,
    rating: 4.7,
    reviewCount: 223,
    location: "Thanh Khê, Đà Nẵng",
    status: "Sẵn sàng nhận thêm",
    amenities: ["Máy lọc không khí", "Camera 24/7"],
    petType: ["cat"],
    personality: ["shy"],
    specialNeeds: ["medication"],
    experienceLevel: "experienced-with-shy",
    diet: ["restricted-food"],
    environment: "indoor-only",
    availability: ["morning"],
    image: "images/home_with_cats.png"
  }
];
